spring:
  application:
    name: Quizz
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        column_ordering_strategy: legacy
  flyway:
    enabled: true
    baseline-on-version: 1
    baseline-on-migrate: false
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: DEBUG
